### ISSUE TITLE
Missing glyphs in Cmder/conEmu

### ISSUE THREAD

**Issue by nikmd23** [lostintangent/azjs#22] opened 2017-05-25 21:27 UTC
After passing the issue I had in #20, I've begun a deployment.

Most of the glyphs appear correctly, there only seems to be one missing:

![image](https://cloud.githubusercontent.com/assets/199026/26471352/fb583e6e-4166-11e7-8193-126d5924062f.png)

I'm not sure if there is anything that can be done about this, but I wanted to let you know.

(The animated glyphs worked to!)

**Comment by lostintangent** [comment] 2017-05-25 22:28
That question mark is actually intentional, since the prompting library displays it as a prefix of prompts (as a standard behavior). If it shows the checkmark and spinner correctly, then it is working as expected :)

**Comment by lostintangent** [comment] 2017-05-25 23:08
I'm going to close this as "by design", since that specific glyph is expected. Re-open this if you notice any other rendering issues. Thanks!

**Closed as completed by lostintangent** 2017-05-25 23:08 UTC

**Comment by nikmd23** [comment] 2017-05-26 15:50
Beautiful!

Yeah, I was expecting a box around a question make to represent a missing glyph, but I thought I'd submit the issue just to be sure. I won't ❓ you again. 😝
